denoland/deno_npm

src/registry.rs
src/resolution/common.rs
src/resolution/graph.rs
src/resolution/mod.rs
src/resolution/snapshot.rs

This will help us do stuff like retry resolution reloading package information in the CLI.

feat: remove generic errors

---

src/lib.rs
src/resolution/graph.rs
src/resolution/snapshot.rs

```rs
// will only contain the packages for a certain system
let valid_serialized_snapshot = snapshot.as_valid_serialized_for_system(&system_info);
```

feat: ability to get a `ValidSerializedNpmResolutionSnapshot` for a system

---

src/resolution/graph.rs
src/resolution/snapshot.rs

refactor: remove api from NpmSnapshot

---

src/resolution/collections.rs
src/resolution/graph.rs
src/resolution/mod.rs
src/resolution/snapshot.rs

fix: support siblings that are peer dependencies of each other

---

Cargo.lock
Cargo.toml
src/resolution/common.rs
src/resolution/graph.rs
src/resolution/snapshot.rs

Waiting on https://github.com/denoland/deno_semver/pull/5

refactor: update deno_semver to 0.3

---

src/resolution/common.rs

Small updates from https://github.com/denoland/deno_npm/pull/37

chore: fixes and test for resolve a version requirement to latest dist tag when matches

---

src/registry.rs
src/resolution/graph.rs

For https://github.com/denoland/deno/issues/20771

fix: handle optional deps not found in dependencies map

---

Cargo.lock
Cargo.toml
rust-toolchain.toml
src/lib.rs
src/registry.rs
src/resolution/mod.rs
src/resolution/snapshot.rs

~~Waiting on https://github.com/denoland/deno_lockfile/pull/13 and https://github.com/denoland/deno_semver/pull/15~~

refactor: updates for smarter lockfile

---

src/lib.rs
src/resolution/graph.rs
src/resolution/snapshot.rs

Required for https://github.com/denoland/deno/pull/23496

feat: add NpmResolutionPackage.bin

---

src/registry.rs

https://github.com/denoland/deno/issues/23776

fix: deserialize registry json with null values to default

---

src/registry.rs

I've gotten better at dealing with this now.

refactor: make `NpmRegistryApi` unsync

---

src/npm_rc/mod.rs
src/resolution/snapshot.rs

Needed for https://github.com/denoland/deno/pull/25107

fix: Remove references to --lock-write flag

---

Cargo.lock
Cargo.toml
benches/bench.rs

This is just for local development.

chore: add basic benching

---

src/resolution/graph.rs

**Before**
Original resolution with duplicate packages (`@aws-sdk/client-sso-oidc`):
**After**

fix: reduce duplicate packages resolving `@aws-sdk/client-s3@3.679.0`

---

Cargo.lock
Cargo.toml
src/resolution/graph.rs
src/resolution/mod.rs
src/resolution/snapshot.rs

For https://github.com/denoland/deno/issues/17263#issuecomment-2749107972

fix: resolve peer deps even when version does not match

---

src/resolution/graph.rs

Test for https://github.com/denoland/deno_npm/pull/93
Made trivially with the help of https://github.com/denoland/deno_npm/pull/95

chore: add test for vite tailwind optional dep issue

---

src/registry.rs
src/resolution/snapshot.rs

For https://github.com/denoland/deno/issues/27758

fix: support packument with no shasum

---

src/resolution/common.rs
src/resolution/graph.rs

Ref https://github.com/denoland/deno/issues/28890

fix: panic when using patch with tag

---

src/resolution/snapshot.rs

This will fix https://github.com/denoland/deno/issues/28366

fix: include all copy packages when collecting packages for system

---

src/registry.rs
src/resolution/graph.rs

Part of https://github.com/denoland/deno/pull/30702

feat: support directories property

---

Cargo.lock
Cargo.toml
src/registry.rs
src/resolution/common.rs
src/resolution/graph.rs

fix: error for tag newer than the newest dependency date
