denoland/deno_npm

- Cargo.toml
- src/resolution/graph.rs
- src/resolution/snapshot.rs
We can remove this now, thanks to Matt's PR adding deno_core::task::spawn.
> refactor: remove `Arc<Mutex<T>>` usages

- src/resolution/graph.rs
This was accidentally doing stuff like the following (note all the axios dependencies for the optional dependencies):
```
"dependencies": {
"@anthropic-ai/sdk": "@anthropic-ai/sdk@0.4.3",
"@aws-sdk/client-dynamodb": "axios@1.4.0",
"@aws-sdk/client-lambda": "axios@1.4.0",
"@aws-sdk/client-s3": "axios@1.4.0",
"@aws-sdk/client-sagemaker-runtime": "axios@1.4.0",
"@clickhouse/client": "axios@1.4.0",
"@getmetal/metal-sdk": "axios@1.4.0",
"@huggingface/inference": "axios@1.4.0",
"@opensearch-project/opensearch": "axios@1.4.0",
"@pinecone-database/pinecone": "axios@1.4.0",
"@supabase/supabase-js": "axios@1.4.0",
"@tensorflow-models/universal-sentence-encoder": "axios@1.4.0",
"@tensorflow/tfjs-converter": "axios@1.4.0",
"@tensorflow/tfjs-core": "axios@1.4.0",
"@zilliz/milvus2-sdk-node": …
```
> fix: better handling of multiple optional peer dependencies

- src/lib.rs
- src/resolution/graph.rs
- src/resolution/snapshot.rs
This has annoyed me. The `pkg_` doesn't really ever help with readability.
> refactor: pkg_id to id

- src/resolution/snapshot.rs
In eszip when we deserialize the npm snapshot we already do some steps that ensure it's valid. For this reason, we can just convert directly to a valid serialized snapshot instead of doing the `into_valid()` runtime checks.
> feat: add SerializedNpmResolutionSnapshot.into_valid_unsafe

- src/resolution/graph.rs
- src/resolution/snapshot.rs
We already know the data in the `NpmResolutionSnapshot` is valid, so the `as_serialized()` should actually be `as_valid_serialized()` then we can have some methods on the valid snapshot for converting to a serialized snapshot.
> feat: NpmResolutionSnapshot - Get valid serialized snapshot

- src/resolution/graph.rs
- src/resolution/mod.rs
- src/resolution/snapshot.rs
Continuation of #17. Removes the `version_resolver` from the NpmResolutionSnapshot.
> refactor: extract pending resolution to separate struct

- src/resolution/mod.rs
- src/resolution/snapshot.rs
Need this for going from a specifier path to an NpmPackageId.
> feat: NpmResolutionSnapshot - resolve_pkg_from_pkg_cache_folder_id

- src/resolution/common.rs
for npm package [await-o-test-pre-release-tag](https://www.npmjs.com/package/await-o-test-pre-release-tag?activeTab=versions)
```
$ npm view await-o-test-pre-release-tag
dist-tags:
alpha: 1.0.0-alpha.3   latest: 1.0.0-alpha.1  next: 3.0.0
```
if we run `deno run -A --node-modules-dir npm:await-o-test-pre-release-tag` it will install version `3.0.0`:
```
$ ls node_modules/.deno
await-o-test-pre-release-tag@3.0.0 node_modules
```
it should install  version `1.0.0-alpha.1` as npm or yarn does.
Alternatively, if the package being installed has only one prerelease version, deno will throw an error:
```
Could not find npm package 'A' matching '*'.
```
> fix: use latest tag version directly if version req is *

- src/resolution/common.rs
Closes #36
Adds logic to return the `latest` tagged version if it is present and satisfies the version requirement.
> fix: resolve a version requirement to the latest dist tag if it matches

- src/npm_rc/mod.rs
Makes it more discoverable (this is for the next time we upgrade).
> refactor: move npmrc parse method to struct

- Cargo.toml
- src/registry.rs
For https://github.com/denoland/deno/issues/23862
```
> deno run --reload index.ts
error: failed reading lockfile 'V:\scratch\deno.lock'
Caused by:
Error getting response at https://registry.npmjs.org/urllib for package "urllib": invalid type: map, expected a string at line 1 column 24565
> ../deno/target/debug/deno run --reload index.ts
┌ ⚠️  Deno requests env access.
├ Run again with --allow-env to bypass this prompt.
└ Allow? [y/n/A] (y = yes, allow; n = no, deny; A = allow all env permissions) >
```
> fix: ignore invalid values in npm registry JSON

- src/npm_rc/mod.rs
Previous when trying to get the registry configuration for `@scope/name` we were
iterating over discovered registry configurations by starting at `<registry_url>/<scope>/<name>`,
trying to get a match, then stripping parts at the end.
This is incorrect, as the configuration should be the exact match on the defined
registry URL for given scope without appending scope and package names.
> fix(npmrc): fix getting registry configuration for a scope

- src/registry.rs
- src/resolution/graph.rs
- src/resolution/mod.rs
- src/resolution/snapshot.rs
No longer necessary because we resolve from deno_graph in a batch. This will simplify things.
I'll integrate this in the CLI before marking this as ready.
> refactor: remove concept of pending resolution

- src/lib.rs
- src/registry.rs
- src/resolution/graph.rs
- src/resolution/snapshot.rs
This PR is compulsory as a first step to address issue [deno repo issue](https://github.com/denoland/deno/issues/24013)
**Changes**
Added deprecated field to related structs in order to delegate deprecation info if found back to deno.
> fix: added deprecated field to the related structs

- src/registry.rs
Will merge this once after the 1.46 release because then the error message will be relevant for Deno 2.0.
Related: https://github.com/denoland/deno/issues/25127
> fix: improve error message when a dependency imports outside of npm

- src/registry.rs
- src/resolution/graph.rs
Part of https://github.com/denoland/deno/issues/25648
> fix: do not get registry info for non-npm packages

- src/registry.rs
- src/resolution/graph.rs
As suggested in https://github.com/denoland/deno/issues/25648#issuecomment-2353962760
> fix: Don't error out on non-existent optional peer dependency

- src/resolution/graph.rs
Fix for https://github.com/denoland/deno/issues/26006
```json
{
"name": "@univerjs/core",
"version": "0.3.0",
"private": false,
"peerDependencies": {
"@univerjs/core": "workspace:*",
},
}
```
> fix: root package has peer dependency on itself

- src/resolution/graph.rs
For https://github.com/denoland/deno/issues/26271
> fix: handle npm dep depending on self when package id has peer dep resolution

- src/resolution/graph.rs
For https://github.com/denoland/deno/issues/28023#issuecomment-2769944224
This reduces traversals of the graph and doesn't re-resolve peer dependnecies when going through the graph again to resolve newly appeared optional peers, which was causing some flip flopping of dependencies.
> fix: further reduce duplicates with optional peers

- benches/bench.rs
- examples/minimal_dep_repro.rs
- examples/minimal_dep_repro/main.rs
Adds a tool to create a minimal reproduction of a bug from a set of real npm package requirements and a provided condition.
1. Update the file at examples/minimal_dep-repro.rs
1. Provide the package requirements.
2. Update the condition saying what the bug is.
3. Run `cargo run --example minimal_dep_repro`
This will output some test code that you can use in order to have a small reproduction of the bug.
> chore: add tool for creating a minimal reproduction from a set of real npm package requirements

- .gitignore
- Cargo.lock
- Cargo.toml
- examples/min_repro_solver.rs
- examples/minimal_repro_solver.rs
Outputs a folder that can be used with https://jsr.io/@david/bench-registry to run a private npm registry and compare the reproduction with other package managers.
> chore: minimal reproduction solver - output folder for local private registry

- src/resolution/mod.rs
- src/resolution/snapshot.rs
Shifts this down from the CLI (seems ok?)
> feat: add NpmRegistryDefaultTarballUrlProvider

- src/registry.rs
- src/resolution/graph.rs
Supports it by ignoring them for npm resolution. This also causes the deps to not end up in the lockfile.
> fix: support bundle dependencies

- src/registry.rs
- src/resolution/graph.rs
It seems like the "bin" object is always populated when publishing in the packument.
> fix: remove directories.bin
